### ISSUE TITLE
App-factory

### ISSUE THREAD

**Issue by rafaelcanovas** [luantorrex/projeto-vaga-backend#2]
https://github.com/luantorrex/projeto-vaga-backend/blob/87a6d47edacdf3589c65e2a47ac3d73771e24336/app/__init__.py#L7

Bom dia Luan, tudo bem?

Qual foi a motivação para não escolher utilizar o padrão recomendado "app-factory" e quais são os benefícios desse padrão a longo prazo?

Abs!

**Comment by luantorrex** [comment]
Olá Rafael, tudo bem e você?

Nesse caso, não segui o padrão "app-factory" para manter o código o mais simples possível para uma execução local. 
Os benefícios de seguir esse padrão a longo prazo, seriam pelo padrão contemplar em uma única aplicação, a criação de múltiplas instâncias da mesma aplicação. O padrão também simplifica os testes nas aplicações com diferentes configurações de ambientes.

**Comment by rafaelcanovas** [comment]
Obrigado Luan!
