### ISSUE TITLE
Referência da API

### ISSUE THREAD

**Issue by rafaelcanovas** [luantorrex/projeto-vaga-backend#3]
https://github.com/luantorrex/projeto-vaga-backend/blob/87a6d47edacdf3589c65e2a47ac3d73771e24336/app/static/swagger.json#L1-L10

Bom dia Luan.

Manter um arquivo separado, dedicado à referência da API pode se tornar um fardo em um projeto grande e que recebe dezenas de alterações diariamente.

Quais ferramentas podemos utilizar para otimizar isto?

Abs!

**Comment by luantorrex** [comment]
Olá Rafael,

Para uma melhor governança da Referência, podemos utilizar a ferramenta SwaggerHUB, reduzindo assim os conflitos que as  alterações diárias poderiam causar, principalmente quando estamos trabalhando em equipe.

**Comment by rafaelcanovas** [comment]
Obrigado Luan!
