### ISSUE TITLE
Brechas de segurança

### ISSUE THREAD

**Issue by rafaelcanovas** [luantorrex/projeto-vaga-backend#4]
https://github.com/luantorrex/projeto-vaga-backend/blob/87a6d47edacdf3589c65e2a47ac3d73771e24336/app/routes.py#L52

Bom dia Luan.

Quais são as brechas de segurança que essa linha de código introduz?

Abs.

**Comment by luantorrex** [comment]
Olá Rafael, tudo bem?

Como a função 'eval' interpreta o input como expressões em Python, essa linha de código abre brechas de segurança para que usuários mal-intencionados enviem comandos que possam por exemplo, apagar diretórios e arquivos na máquina onde a aplicação está sendo executada.

**Comment by rafaelcanovas** [comment]
Obrigado Luan!
